### ISSUE TITLE
Allow configuring behavior of AllFilter

### ISSUE THREAD

**Issue by Aaron1011** [KyoriPowered/fragment#1]
Currently, `AllFilter` succeeds even if some of its children return `Abstain`. It's sometimes useful to require that every child filter return `ALLOW`.

It would be useful if `AllFilter` allowed configuring this behavior via a constructor parameter.

**Comment by kashike** [comment]
This is intentional - `ABSTAIN` is returned when a filter is not able to process the query it is given: a `ColorFilter` cannot handle a `ShapeQuery`. 


I'd recommend creating your own version of the filter if you, for some weird reason, require this.
